# ~/.config/starship.toml

[character]
success_symbol = "[âœ”](bold green)"
error_symbol = "[âœ–](bold red)"

[line_break]
disabled = true

# Customize the branch symbol
[git_branch]
symbol = "ğŸŒ¿"  # Change to your desired symbol

# Customize the repository state symbols
#[git_status]
#conflicted = "ğŸ”´"
#ahead = "ğŸ”º"
#behind = "ğŸ”»"
#diverged = "ğŸ”€"
#untracked = "â“"
#stashed = "ğŸ“¦"
#modified = "âœï¸"
#staged = "âœ”ï¸"
#renamed = "ğŸ”„"
#deleted = "âŒ"
